CREATE TABLE IF NOT EXISTS noticias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    link VARCHAR(500) NOT NULL UNIQUE,
    categoria VARCHAR(50) NOT NULL,
    eh_relevante BOOLEAN DEFAULT FALSE,
    data_publicacao DATE NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);